import { SkyPreset } from '../../types/level';

export type ParticleKind =
  | 'pollen'
  | 'leaves'
  | 'sparkles'
  | 'dust'
  | 'snow'
  | 'embers'
  | 'rain'
  | 'gold'
  | 'petals'
  | 'none';

/** Art direction per sky preset: sky gradient, celestial bodies, horizon layers, ambience. */
export interface SkyLook {
  zenith: string;
  horizon: string;
  ground: string;
  sun: string;
  /** Visual sun direction (x, y, z); not the shadow light. */
  sunDir: [number, number, number];
  sunSize: number;
  /** 0..1 */
  stars: number;
  /** 0..1 cloud cover in the sky dome */
  clouds: number;
  cloudTint: string;
  aurora: number;
  auroraColor: string;
  /** Distant mountain silhouettes: near / far colour and snow caps. */
  ridgeNear: string;
  ridgeFar: string;
  snow: number;
  /** Cloud-sea colour below the course. */
  cloudSea: string;
  ocean: boolean;
  particles: ParticleKind;
  particleColor: string;
}

export const SKY_LOOKS: Record<SkyPreset, SkyLook> = {
  day: {
    zenith: '#1257c4',
    horizon: '#86c9f4',
    ground: '#6aa5d4',
    sun: '#fff4c2',
    sunDir: [0.35, 0.32, -1],
    sunSize: 1,
    stars: 0,
    clouds: 0.55,
    cloudTint: '#ffffff',
    aurora: 0,
    auroraColor: '#34d399',
    ridgeNear: '#5b7f9e',
    ridgeFar: '#8fbce0',
    snow: 0.8,
    cloudSea: '#e4f1fc',
    ocean: true,
    particles: 'pollen',
    particleColor: '#fff7cc',
  },
  sunset: {
    zenith: '#2e1065',
    horizon: '#fb923c',
    ground: '#7c2d12',
    sun: '#ffd27a',
    sunDir: [0.1, 0.07, -1],
    sunSize: 1.6,
    stars: 0.25,
    clouds: 0.6,
    cloudTint: '#fda4af',
    aurora: 0,
    auroraColor: '#f472b6',
    ridgeNear: '#4a1d4f',
    ridgeFar: '#a4466a',
    snow: 0.3,
    cloudSea: '#fdba74',
    ocean: true,
    particles: 'petals',
    particleColor: '#fecdd3',
  },
  neon: {
    zenith: '#03040c',
    horizon: '#312e81',
    ground: '#0b0a1f',
    sun: '#f72585',
    sunDir: [0, 0.18, -1],
    sunSize: 2.2,
    stars: 1,
    clouds: 0.15,
    cloudTint: '#7c3aed',
    aurora: 0.35,
    auroraColor: '#00f5d4',
    ridgeNear: '#140f33',
    ridgeFar: '#3b1d6e',
    snow: 0,
    cloudSea: '#312e81',
    ocean: false,
    particles: 'sparkles',
    particleColor: '#00f5d4',
  },
  aurora: {
    zenith: '#010d14',
    horizon: '#0f3b3a',
    ground: '#020617',
    sun: '#d1fae5',
    sunDir: [-0.4, 0.28, -1],
    sunSize: 0.8,
    stars: 1,
    clouds: 0.2,
    cloudTint: '#1e3a3a',
    aurora: 1,
    auroraColor: '#34d399',
    ridgeNear: '#0b1f24',
    ridgeFar: '#1d4747',
    snow: 0.9,
    cloudSea: '#134e4a',
    ocean: true,
    particles: 'snow',
    particleColor: '#e0fff6',
  },
  citadel: {
    zenith: '#07090f',
    horizon: '#7c2d12',
    ground: '#1c0a05',
    sun: '#fde047',
    sunDir: [0.3, 0.12, -1],
    sunSize: 1.3,
    stars: 0.7,
    clouds: 0.35,
    cloudTint: '#9a3412',
    aurora: 0,
    auroraColor: '#f59e0b',
    ridgeNear: '#1c1008',
    ridgeFar: '#5b2410',
    snow: 0,
    cloudSea: '#7c2d12',
    ocean: false,
    particles: 'embers',
    particleColor: '#fbbf24',
  },
  forest: {
    zenith: '#1f6f4a',
    horizon: '#d9f7c6',
    ground: '#6b8f5a',
    sun: '#fff6cf',
    sunDir: [0.5, 0.36, -1],
    sunSize: 1,
    stars: 0,
    clouds: 0.45,
    cloudTint: '#f7fee7',
    aurora: 0,
    auroraColor: '#bef264',
    ridgeNear: '#2f5a3f',
    ridgeFar: '#8ab89a',
    snow: 0.5,
    cloudSea: '#ecfccb',
    ocean: false,
    particles: 'leaves',
    particleColor: '#bef264',
  },
  cave: {
    zenith: '#07030f',
    horizon: '#4c1d95',
    ground: '#12051f',
    sun: '#f0abfc',
    sunDir: [-0.3, 0.4, -1],
    sunSize: 0.7,
    stars: 1,
    clouds: 0.2,
    cloudTint: '#6d28d9',
    aurora: 0.6,
    auroraColor: '#e879f9',
    ridgeNear: '#1e0b3a',
    ridgeFar: '#4c1d95',
    snow: 0,
    cloudSea: '#581c87',
    ocean: false,
    particles: 'sparkles',
    particleColor: '#f5d0fe',
  },
  desert: {
    zenith: '#b4531c',
    horizon: '#fde7a6',
    ground: '#d9a066',
    sun: '#fffbeb',
    sunDir: [0.2, 0.45, -1],
    sunSize: 1.2,
    stars: 0,
    clouds: 0.2,
    cloudTint: '#fff7ed',
    aurora: 0,
    auroraColor: '#fbbf24',
    ridgeNear: '#9a4a1c',
    ridgeFar: '#e0a36a',
    snow: 0,
    cloudSea: '#fde2b3',
    ocean: false,
    particles: 'dust',
    particleColor: '#fcd9a8',
  },
  glacier: {
    zenith: '#0c4a6e',
    horizon: '#e3f4ff',
    ground: '#b6d6ea',
    sun: '#f5fbff',
    sunDir: [0.3, 0.3, -1],
    sunSize: 0.9,
    stars: 0,
    clouds: 0.5,
    cloudTint: '#ffffff',
    aurora: 0,
    auroraColor: '#7dd3fc',
    ridgeNear: '#6d8fae',
    ridgeFar: '#c4dcef',
    snow: 1,
    cloudSea: '#f8fbff',
    ocean: false,
    particles: 'snow',
    particleColor: '#ffffff',
  },
  gale: {
    zenith: '#1e3a8a',
    horizon: '#d6dee8',
    ground: '#7b8aa0',
    sun: '#eef2ff',
    sunDir: [-0.2, 0.4, -1],
    sunSize: 0.9,
    stars: 0,
    clouds: 0.85,
    cloudTint: '#e2e8f0',
    aurora: 0,
    auroraColor: '#93c5fd',
    ridgeNear: '#48566b',
    ridgeFar: '#95a3b8',
    snow: 0.8,
    cloudSea: '#e2e8f0',
    ocean: false,
    particles: 'dust',
    particleColor: '#f1f5f9',
  },
  volcano: {
    zenith: '#120604',
    horizon: '#b8401a',
    ground: '#2a0d06',
    sun: '#ff9a4d',
    sunDir: [0.2, 0.15, -1],
    sunSize: 1.8,
    stars: 0.35,
    clouds: 0.7,
    cloudTint: '#4a1d10',
    aurora: 0,
    auroraColor: '#f97316',
    ridgeNear: '#1a0906',
    ridgeFar: '#5a1f10',
    snow: 0,
    cloudSea: '#3b1206',
    ocean: false,
    particles: 'embers',
    particleColor: '#ff8a3d',
  },
  storm: {
    zenith: '#0b1120',
    horizon: '#566579',
    ground: '#1e293b',
    sun: '#cffafe',
    sunDir: [0.1, 0.35, -1],
    sunSize: 0.6,
    stars: 0,
    clouds: 1,
    cloudTint: '#334155',
    aurora: 0,
    auroraColor: '#67e8f9',
    ridgeNear: '#1b2536',
    ridgeFar: '#3f4c60',
    snow: 0.6,
    cloudSea: '#334155',
    ocean: false,
    particles: 'rain',
    particleColor: '#bfe9ff',
  },
  summit: {
    zenith: '#1e1b4b',
    horizon: '#ffd98a',
    ground: '#9a6b2f',
    sun: '#fff7d6',
    sunDir: [0.25, 0.1, -1],
    sunSize: 1.5,
    stars: 0.8,
    clouds: 0.35,
    cloudTint: '#fde68a',
    aurora: 0.25,
    auroraColor: '#fbbf24',
    ridgeNear: '#3a2f6b',
    ridgeFar: '#b08a7a',
    snow: 1,
    cloudSea: '#fff1c9',
    ocean: false,
    particles: 'gold',
    particleColor: '#fde68a',
  },
};
